# Generated by Django 4.2.9 on 2024-03-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('PhoneNumber', models.IntegerField()),
                ('Email', models.CharField(max_length=40)),
                ('passsword', models.CharField(max_length=50)),
                ('slug', models.SlugField(default='')),
            ],
        ),
    ]
