# Generated by Django 4.2.9 on 2024-03-15 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BakersApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='passsword',
            new_name='password',
        ),
    ]
