# Generated by Django 4.2.9 on 2024-03-16 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BakersApp', '0005_categorymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='static/images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BakersApp.categorymodel')),
            ],
        ),
    ]
